// Generated by CoffeeScript 1.11.1
(function() {
  var displayPaymentMethods, startPaymentFlow;

  startPaymentFlow = function() {
    var amount;
    window.senderHash = PagSeguroDirectPayment.getSenderHash();
    amount = parseFloat($('input[name=giftPrice]:checked', '#quota').val());
    console.log(amount);
    PagSeguroDirectPayment.getPaymentMethods({
      amount: amount,
      complete: displayPaymentMethods
    });
  };

  displayPaymentMethods = function(response) {
    console.log('displayPaymentMethods');
    if (!response.error) {
      console.log(response.paymentMethods);
    }
  };

  PagSeguroDirectPayment.setSessionId('0a89a3cb287444e59066e4053f6a83f9');

  $(document).ready(function() {
    $('#quota input').on('change', function() {
      console.log('valor', $('input[name=giftPrice]:checked', '#quota').val());
    });
  });

}).call(this);
