// Generated by CoffeeScript 1.11.1
(function() {
  var getGiftPriceAmount,
    hasProp = {}.hasOwnProperty;

  window.PagSeguro = {
    sessionId: '0a89a3cb287444e59066e4053f6a83f9',
    imageHost: 'https://stc.pagseguro.uol.com.br',
    image: {}
  };

  getGiftPriceAmount = function() {
    return parseFloat($('input[name=giftPrice]:checked', '#quota').val());
  };

  PagSeguro.startPaymentFlow = function(event) {
    this.senderHash = PagSeguroDirectPayment.getSenderHash();
    PagSeguroDirectPayment.getPaymentMethods({
      amount: getGiftPriceAmount(),
      complete: this.paymentMethodsCallback
    });
    event.preventDefault();
  };

  PagSeguro.paymentMethodsCallback = function(response) {
    if (response.error) {
      console.log('1. paymentMethodsCallback -> error');
    } else {
      console.log('1. paymentMethodsCallback -> ok');
      PagSeguro.setPaymentMethods(response);
    }
  };

  PagSeguro.setPaymentMethods = function(response) {
    var imageObject, imageSize, methodParams, paymentMethod, ref, results, specificMethod, specificOptions;
    this.APIResponse = response;
    this.paymentMethods = {};
    ref = response.paymentMethods;
    results = [];
    for (paymentMethod in ref) {
      if (!hasProp.call(ref, paymentMethod)) continue;
      methodParams = ref[paymentMethod];
      this.paymentMethods[paymentMethod] = {};
      results.push((function() {
        var ref1, results1;
        ref1 = methodParams.options;
        results1 = [];
        for (specificMethod in ref1) {
          if (!hasProp.call(ref1, specificMethod)) continue;
          specificOptions = ref1[specificMethod];
          this.paymentMethods[paymentMethod][specificMethod] = {};
          results1.push((function() {
            var ref2, results2;
            ref2 = specificOptions.images;
            results2 = [];
            for (imageSize in ref2) {
              if (!hasProp.call(ref2, imageSize)) continue;
              imageObject = ref2[imageSize];
              results2.push(this.paymentMethods[paymentMethod][specificMethod][imageSize] = this.imageHost + imageObject.path);
            }
            return results2;
          }).call(this));
        }
        return results1;
      }).call(this));
    }
    return results;
  };

  $(document).ready(function() {
    PagSeguroDirectPayment.setSessionId(PagSeguro.sessionId);
    $('#quota input').on('change', function() {
      return console.log('valor', getGiftPriceAmount());
    });
  });

}).call(this);
